config/routes.rb
Metube::Application.routes.draw do
  root 'videos#index'
  resources :videos
  resources :sounds
  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, :polymorphic => true
end

app/models/sound.rb
class Sound < ActiveRecord::Base
  has_many :comments, :as => :commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
end

app/models/video.rb
class Video < ActiveRecord::Base
  has_many :comments, :as => :commentable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to :back
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:message, :commentable_id, :commentable_type)
  end
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
	def index
    @sounds = Sound.all
  end

  def show
    @sound = Sound.find(params[:id])
    @comments = @sound.comments
    @comment = @sound.comments.new
  end

  def new
    @sound = Sound.new
  end

  def edit
    @sound = Sound.find(params[:id])
  end

  def create
    @sound = Sound.find(params[:id])
    @sound.update(sound_params)
    redirect_to @sound
  end

  def update
    @sound = Sound.find(params[:id])
    @sound.update(sound_params)
    redirect_to @sound
  end

  def destroy
    @sound = Sound.find(params[:id])
    @sound.destroy
    redirect_to :index
  end

  private
  def sound_params
    params.require(:sound).permit(:title, :soundcloud_url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(:id)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all
  end

  def show
    @video = Video.find(params[:id])
    @comments = @video.comments
    @comment = @video.comments.new
  end

  def new
    @video = Video.new
  end

  def edit
    @video = Video.find(params[:id])
  end

  def create
    video = Video.new(video_params)
    video.save
    redirect_to @video
  end

  def update
    @video = Video.find(params[:id])
    @video.update(video_params)
    redirect_to @video
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to :index
  end

  private
  def video_params
    params.require(:video).permit(:title, :description, :youtube_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sound_helper.rb
module SoundHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Metube</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sounds/edit.html.erb
<h1>Edit a Sound</h1>

<form action=<%="/sounds/#{params[:id]}"%> method="post">
  <input name="_method" type="hidden" value="put">
  Title: <input type="text" name="sound[title]"><br>
  Soundcloud URL: <input type="text" name="sound[soundcloud_url]"><br>
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <input type="submit" value="submit">
</form>

app/views/sounds/index.html.erb
<h1>Sound#index</h1>
<%= link_to "Videos", videos_path %><br>
<%= link_to "Create a new sound", new_sound_path %>
<br><br><br>

<% @sounds.each do |sound| %>
<%= link_to sound.title, sound %> <br>
  <object height="81" width="100%" id="yourPlayerId" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000">
    <param name="movie" value="http://player.soundcloud.com/player.swf?url=<%= sound.soundcloud_url %>&enable_api=true&object_id=yourPlayerId"></param>
    <param name="allowscriptaccess" value="always"></param>
    <embed allowscriptaccess="always" height="81" src="http://player.soundcloud.com/player.swf?url=<%= sound.soundcloud_url %>&enable_api=true&object_id=yourPlayerId" type="application/x-shockwave-flash" width="100%" name="yourPlayerId"></embed>
  </object>
  <br>
<% end %>

app/views/sounds/new.html.erb
<h1>Edit a Sound</h1>

<form action=<%="/sounds/#{params[:id]}"%> method="POST">
  <input name="_method" type="hidden" value="post">
  Title: <input type="text" name="sound[title]"><br>
  Soundcloud URL: <input type="text" name="sound[soundcloud_url]"><br>
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <input type="submit" value="submit">
</form>

app/views/sounds/show.html.erb
<h1>Sounds#show</h1>
<%= link_to "Edit this sound", edit_sound_path(@sound) %>
<%= link_to "Destroy this sound", {action: :destroy, id: @sound.id}, method: :delete %>
<br>
<br>
<br>

<%= @sound.title %> </br>

  <object height="81" width="100%" id="yourPlayerId" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000">
    <param name="movie" value="http://player.soundcloud.com/player.swf?url=<%= @sound.soundcloud_url %>&enable_api=true&object_id=yourPlayerId"></param>
    <param name="allowscriptaccess" value="always"></param>
    <embed allowscriptaccess="always" height="81" src="http://player.soundcloud.com/player.swf?url=<%= @sound.soundcloud_url %>&enable_api=true&object_id=yourPlayerId" type="application/x-shockwave-flash" width="100%" name="yourPlayerId"></embed>
  </object>
 </br>

 <%= form_for @comment do |f| %>
  <%= f.text_field :message %>
  <%= f.hidden_field :commentable_id, :value => @comment.commentable.id %>
  <%= f.hidden_field :commentable_type, :value => @comment.commentable.class.to_s %>
  <%= f.submit :message %>
<% end %>

<ul>

  <% @sound.comments.each do |comment| %>
    <li><%= comment.message %></li>
  <% end %>

</ul>

app/views/users/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

<% @users.each do |user| %>
<%= user.name %> <br/>
<%= user.email %> <br/>
<br/>
<% end %>

app/views/users/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>

app/views/videos/edit.html.erb
<h1>Video form</h1>

<form action=<%="/videos/#{params[:id]}"%> method="post">
  <input name="_method" type="hidden" value="put">
  Title: <input type="text" name="video[title]"><br>
  Description: <input type="text" name="video[description]"><br>
  Youtube ID: <input type="text" name="video[youtube_id]"><br>
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <input type="submit" value="submit">
</form>

app/views/videos/index.html.erb
<h1>Video#index</h1>
<%= link_to "Sounds", sounds_path %><br>
<%= link_to "Create a new video", new_video_path %>
<br><br><br>

<% @videos.each do |video| %>
<%= link_to video.title, video %> <br>
<%= video.description %> <br>
<iframe width="560" height="315" src="//www.youtube.com/embed/<%=video.youtube_id%>" frameborder="0" allowfullscreen></iframe><br>
<% end %>

app/views/videos/new.html.erb
<h1>Edit a video</h1>
<p>Find me in app/views/videos/new.html.erb</p>

<form action=<%="/videos/#{params[:id]}"%> method="POST">
  <input name="_method" type="hidden" value="post">
  Title: <input type="text" name="video[title]"><br>
  Description: <input type="text" name="video[description]"><br>
  Youtube ID: <input type="text" name="video[youtube_id]"><br>
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <input type="submit" value="submit">
</form>

app/views/videos/show.html.erb
<h1>Videos#show</h1>
<p>Find me in app/views/video/show.html.erb</p>
<%= link_to "Edit this video", edit_video_path(@video) %>
<%= link_to "Destroy this video", {action: :destroy, id: @video.id}, method: :delete %>
<br>
<br>
<br>

<%= @video.title %> </br>
<%= @video.description %> </br>
<iframe width="560" height="315" src="//www.youtube.com/embed/<%=@video.youtube_id%>" frameborder="0" allowfullscreen></iframe> </br>

<%= form_for @comment do |f| %>
  <%= f.text_field :message %>
  <%= f.hidden_field :commentable_id, :value => @comment.commentable.id %>
  <%= f.hidden_field :commentable_type, :value => @comment.commentable.class.to_s %>
  <%= f.submit :message %>
<% end %>

<ul>

  <% @video.comments.each do |comment| %>
    <li><%= comment.message %></li>
  <% end %>

</ul>